### ISSUE TITLE
Unable to run this repo

### ISSUE THREAD

**Issue by pen9u1nlee** [andreea-alexandru/private-data-driven-control#1]
Hello Dr Alexandru, I have some troubles in running this repo. 
My steps are listed below: 
1. PALISADE v1.9.1 is installed globally. 
2. `CmakeLists.User.txt` is copied to this repo's root directory and configured following the README in PALISADE. 
3. Remote includes like `#include "../../core/lib/math/matrix.cpp"` in `Plant.h` are fixed locally with `#include "matrix.cpp"`. 

However errors occur upon making executables and there are some questions: 
* Where is `ckks.cpp` which is included in `ckks-impl.cpp`? I didn't find it neither in PALISADE nor in this repo. 
* I want to know whether I configure this repo in a proper way. E.g. in step 3, should I copy these head files into the PALISADE library?

Fantastic Data-driven Predictive Control work by the way :)

**Comment by andreea-alexandru** [comment]
Hi!

- ckks.cpp is included in the PALISADE repository https://gitlab.com/palisade/palisade-development/-/tree/v1.9.1/src/pke/lib/scheme/ckks .
- I had the source files (data-driven-control.cpp, Plant.h, helper-control.h) in the src/pke/examples folder; I recall I had a problem with the CmakeLists.User.txt at the time and that's why I preferred to compile the examples folder.
- The modifications I highlight in matrix.cpp need to be made in the existing file at ../../core/lib/math/matrix.cpp, i.e., matrix.cpp should not be a local file. The same holds for the highlighted modifications for matrix.h, pubkey.h, cryptocontext.h, ckks.h, ckks-impl.cpp.

There are two things worth mentioning. First, in the repository here https://github.com/andreea-alexandru/swift-private-data-driven-control (but with the same description for running it), there is a better version of roughly the same problem. Second, there have been tremendous improvements in more recent PALISADE versions, both in terms of substantial low-level optimizations and user-friendliness. So I suggest that if you want to implement your own project, you use a newer version. 

Hope this helps!

**Comment by pen9u1nlee** [comment]
Thanks for your reply! It works!
